version: 2
updates:
  - package-ecosystem: "composer"
    directory: "/sites/all/libraries/twilio"
    schedule:
      interval: "weekly"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
