<?php


/**
 * Implements hook_form().
 */

/**
 * Implements hook_twilio_sms_incoming().
 */
function legalaid_sms_twilio_sms_incoming($sms, $options) {
  $number = $sms['number'];
  $number_twilio = $sms['number_twilio'];
  $message = strtolower($sms['message']);
  watchdog('SMS','An sms was received from @num',array('@num' => $number),WATCHDOG_NOTICE);

  $exact_match = legalaid_sms_find_match($message);
  if (!empty($exact_match)) {
    watchdog('SMS','We found a match',array(),WATCHDOG_NOTICE);

    twilio_send($number, 'We found a match');
  }
  else {
    watchdog('SMS','No match',array(),WATCHDOG_NOTICE);

    twilio_send($number, 'We did not find a match');
  }

}


function legalaid_sms_find_match($message) {
  $query = new entityFieldQuery();
  $query->entityCondition('entity_type','node')
    ->propertyCondition('status',NODE_PUBLISHED)
    ->propertyCondition('type','sms_info')
  ->fieldCondition('field_keyword','value',$message,'=')
    ->addMetaData('account', user_load(1));

$result = $query->execute();
if (isset($result['node'])) {
  $matching_items_nids = array_keys($result['node']);
  $matching_items = entity_load('node', $matching_items_nids);
  return $matching_items;
}
return null;



}

/**
 * Implements hook_form_alter().
 */
function legalaid_sms_form_alter(&$form, &$form_state, $form_id) {

}

