<?php

/**
 * Implements hook_form_alter().
 */
function legalaid_sms_content_form_alter(&$form, &$form_state, $form_id) {
  $message = 'court tips';
  $exact_match = legalaid_sms_find_match($message);
  dpm($exact_match);
  watchdog('SMS','We found a match @count',array('@count' => count($exact_match)),WATCHDOG_NOTICE);
  if (count($exact_match) == 1) {
    $message = legalaid_sms_prepare_content(current($exact_match));
    dpm($message);
  }
  else {
    //send something else
  }
}


function legalaid_sms_strip_html($text) {
  $text = str_replace('[no-lexicon]','', $text);
  $text = str_replace('[/no-lexicon]','', $text);
  $text = str_replace('<a href="/node',' http://dev-hackathon-sms.pantheonsite.io/node',$text);
  $text = str_replace('<a href="es/node',' http://dev-hackathon-sms.pantheonsite.io/es/node',$text);
  $text = str_replace('<a href="',' ',$text);
  $text = str_replace('">',' ',$text);
  $text = str_replace('<p>'," \n ",$text);
  $text = str_replace('<h3>'," \n ",$text);
  $text = str_replace('<h4>'," \n ",$text);
  $text = str_replace('<h5>'," \n ",$text);
  $text = str_replace('&nbsp;'," ",$text);
  $text = str_replace('<li>'," \n*",$text);
  $text = str_replace('<ul>'," \n",$text);
  $text = decode_entities($text);


  $text = strip_tags($text);
  return $text;
}

function legalaid_sms_prepare_content($node) {
  $message = $node->title;
  $message .= '\n';

  $message .= legalaid_sms_strip_html($node->body['und'][0]['safe_value']);
  if(!empty($message)) {
    twilio_send(6308811337,$message);
  }
  return $message;
}
